### ISSUE TITLE
vNode build process stops during building "openipmi".

### ISSUE THREAD

**Issue by rva818** [InfraSIM/idic#57]
**[Problem Description]**
I’m trying to depoly InfraSIM on ESXi.
But vNode packages/binarys files cannot be built because the build process stops during building "openipmi".

**[Steps to Reproduce]**
1) git clone https://github.com/InfraSIM/idic.git

2) on idic directory, run the following command.
`$ sudo make setupenv`

3) on idic/vcompute/vnode directory, run the following command.
`$ sudo fakeroot make menuconfig`

4) on idic/vcompute/vnode directory, run the following command.
`$ sudo fakeroot make`

**[Actual Results]**
Build fails and the following messages were displayed.
```
**** Now Building: openipmi

make -C /home/onon/idic/vcompute/vnode/../../pdk/content/build -f /home/onon/idic/vcompute/vnode/../../pdk/content/mkfiles/openipmi.mk
make[2]: Entering directory `/home/onon/idic/pdk/content/build'
git clone OpenIPMI into OpenIPMI-master
Cloning into 'OpenIPMI-master'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
Unexpected end of command stream
make[2]: *** [OpenIPMI-master] Error 128
make[2]: Leaving directory `/home/onon/idic/pdk/content/build'
make[1]: *** [openipmi] Error 2
make[1]: Leaving directory `/home/onon/idic/vcompute/vnode'
make: *** [.root_complete] Error 2
```

Operation Log:
[20161012-01.txt](https://github.com/InfraSIM/idic/files/525991/20161012-01.txt)

**[Expected Results]**
Build success and idic/pdk/linux/vnode includes “config-3.16.0”, “ramfs.lzma”, “System.map-3.16.0” and “vmlinuz-3.16.0”.

**Comment by fub2** [comment]
@rva818 build is break is because process is checking out a branch that doesn't exist in https://github.com/InfraSIM/idic/blob/master/pdk/content/mkfiles/openipmi.mk

`BRANCH:=master` 

change "master" to "infrasim-openipmi-2.0.22" should work.

And we highly recommend to move to InfraSIM/infrasim-compute for a server simulation instead of building everything from what idic repo has. Post at https://groups.google.com/forum/#!forum/infrasim has all details.

**Comment by rva818** [comment]
@fub2 thank you for your support always.
Building works well. And I’ll use InfraSIM/infrasim-compute.
